alter table public.vocabulary_items
add column if not exists word_number bigint generated by default as identity;

create unique index if not exists idx_vocabulary_items_word_number
on public.vocabulary_items(word_number);
